### ISSUE TITLE
Fix liminal gap on dropdowns

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#186]
Dropdowns are rendering with an extra 2px of height. This is because the space between the sub components has a font size.

Proposed solution:

```css
.cf-dropdown {
    font-size: 0;
}
```
